config/routes.rb
SassTime::Application.routes.draw do

resources :episodes 
root 'episodes#index'
resources :users, only: [:index, :create, :new, :edit, :show, :update]
resources :auths, only: [:create, :new]

delete "auths" => "auths#destroy"

  

end

app/models/episode.rb
class Episode
  include Mongoid::Document
  field :number, type: Float
  field :title, type: String
  field :directed_by, type: String
  field :first_aired, type: Time

  validates :number, uniqueness: true, presence: true
end

app/models/user.rb
#load and use bcrypt engine
require 'bcrypt'
class User
  include Mongoid::Document
  
  #attr_accessors are the getters and setters, we need to get/set the password
  attr_accessor :password

  field :username,        type: String
  field :salt,            type: String
  field :hashed_password, type: String

  before_save :hash_stuff

  def authenticated?(pwd)
  	self.hashed_password == 
  	BCrypt::Engine.hash_secret(pwd, self.salt)
  end

  private
  #hash the password
  def hash_stuff
  	#generate salt
  	self.salt = BCrypt::Engine.generate_salt
  	#hash it
  	self.hashed_password = BCrypt::Engine.hash_secret(password, self.salt)
  	#get rid of the actual password, so set it to nil
  	self.password = nil
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  # Who is currently logged in, if anyone
  def current_user
  	if session[:user_id]
  		User.find_by(id: session[:user_id])
  	end
  end

end

app/controllers/auths_controller.rb
class AuthsController < ApplicationController

	# Show a login form
	def new
		if current_user
			redirect_to root_path
		else
			# Make a login form from an object that has username and password
			@user = User.new
		end
	end

	# Log them in!
	def create
		user = User.find_by(username: params[:user][:username])
		if user.authenticated?(params[:user][:password])
			session[:user_id] = user.id
			redirect_to root_path
		end
	end

	# Log out
	def destroy
		session[:user_id] = nil
		redirect_to new_auth_path
	end

end

app/controllers/episodes_controller.rb
class EpisodesController < ApplicationController
  
  def index
  	@episodes = Episode.all
  end
  
  def destroy
  	Episode.find(params[:id]).destroy
	redirect_to episodes_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def index
		@users = User.all
	end

	def new
		@user = User.new
	end

	def show
		@user = User.find(params[:user])
	end

def create
		User.create(params.require(:user).permit(:username, :password))
		redirect_to users_path
	end

	def edit
		@user = User.find(params[:user])
	end

end


  # def create
  # 	@art_car = ArtCar.new(art_car_params)

  # 	if @art_car.save
  # 		flash[:notice] = "Successfully created art car!"
  # 		redirect_to action: 'index'
  # 	else
  # 		render action: 'new'
  # 	end
  # end

 
  # def update
  #   @art_car = ArtCar.find(params[:id])

  #   if @art_car.update(art_car_params)
  #     flash[:notice] = "Successfully updated art car!"
  #     redirect_to action: 'index'
  #   else
  #     render action: 'edit'
  #   end  
  # end

  # def destroy
  #   ac = Array.find(params[:id])
  #   ac.destroy
  #   redirect_to art_cars_path
  #   flash[:notice] = "Successfully deleted art car!"

  #  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/auths_helper.rb
module AuthsHelper
end

app/helpers/episodes_helper.rb
module EpisodesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/auths/new.html.erb
<div class="login">
	<h1>Log In</h1>
	<%= form_for @user, {url:"/auths", method:"post"} do |u|%>
	<%= u.text_field :username, :placeholder => "Your username" %><br>
	<%= u.password_field :password, :placeholder => "Your password" %><br>
	<%= u.submit "Log In" %>
	<%end%>
</div>

app/views/episodes/index.html.erb
<div class="main">

	<h1>Season One Episodes <%= current_user ? current_user.username : "(not logged in)" %> </h1>

	<%= button_to "Log out", auths_path, method: :delete %>

	<% @episodes.each do |e| %>

		<div class="episode">
			<%= e.number %> -- <%= e.title %>
			<%= link_to "X", e, {method: :delete} %>
			<%= button_to "X", e, {method: :delete} %>
		</div>
		<div class="details">
			Directed by <%= e.directed_by %>. First aired on <%=e.first_aired.strftime '%B %d, %Y' %>.
		</div>

	<% end %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SassTime</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<header></header>

	<%= yield %>
<%= debug(params) if Rails.env.development? %>
</body>
</html>

app/views/users/index.html.erb
<h1>List of Users</h1>
    <ul>
      <% @users.each do |user| %>
      <li><%= user.username %></li>
        <% end %>
    </ul>

app/views/users/new.html.erb
<div class="createuser">
	<h1>Create a New User</h1>
	<%=form_for @user do |f|%>
		<%=f.text_field :username, :placeholder => "Enter your username"%><br>
		<%=f.password_field :password, :placeholder => "Enter password" %><br>
		<%= f.submit "Create New User" %>
	<% end %>
</div>